In [11]:
import matplotlib.pyplot as plt
import pandas as pd
from scipy.stats import zscore
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC

# this line allows the graphs to be displayed inside the jupyter notebook
%matplotlib inline

In [5]:
ecg_data = pd.read_csv("ecg.csv", header=None)
ecg_data.head()


0         1         2         3         4         5         6    \
0 -0.112522 -2.827204 -3.773897 -4.349751 -4.376041 -3.474986 -2.181408   
1 -1.100878 -3.996840 -4.285843 -4.506579 -4.022377 -3.234368 -1.566126   
2 -0.567088 -2.593450 -3.874230 -4.584095 -4.187449 -3.151462 -1.742940   
3  0.490473 -1.914407 -3.616364 -4.318823 -4.268016 -3.881110 -2.993280   
4  0.800232 -0.874252 -2.384761 -3.973292 -4.338224 -3.802422 -2.534510   

        7         8         9    ...       131       132       133       134  \
0 -1.818286 -1.250522 -0.477492  ...  0.792168  0.933541  0.796958  0.578621   
1 -0.992258 -0.754680  0.042321  ...  0.538356  0.656881  0.787490  0.724046   
2 -1.490659 -1.183580 -0.394229  ...  0.886073  0.531452  0.311377 -0.021919   
3 -1.671131 -1.333884 -0.965629  ...  0.350816  0.499111  0.600345  0.842069   
4 -1.783423 -1.594450 -0.753199  ...  1.148884  0.958434  1.059025  1.371682   

        135       136       137       138       139  140  
0  0.257740  0.228077  0.123431  0.925286  0.193137  1.0  
1  0.555784  0.476333  0.773820  1.119621 -1.436250  1.0  
2 -0.713683 -0.532197  0.321097  0.904227 -0.421797  1.0  
3  0.952074  0.990133  1.086798  1.403011 -0.383564  1.0  
4  1.277392  0.960304  0.971020  1.614392  1.421456  1.0  

[5 rows x 141 columns]

In [10]:
shape = ecg_data.shape 
print("The data set has", shape[0],"data Points")
print("The data set has", shape[1],"Variable")

The data set has 4998 data Points
The data set has 141 Variable


The data have 140 Variables and 4998 Observations

In [7]:
ecg_data.describe()

0            1            2            3            4    \
count  4998.000000  4998.000000  4998.000000  4998.000000  4998.000000   
mean     -0.262502    -1.649828    -2.492623    -3.119754    -3.167656   
std       1.152450     1.445542     1.386457     1.302921     1.104535   
min      -6.729499    -7.090374    -5.132459    -5.363241    -5.375715   
25%      -1.004220    -2.701936    -3.668585    -4.227337    -4.007630   
50%      -0.297541    -1.661892    -2.586129    -3.388210    -3.469899   
75%       0.499909    -0.677998    -1.514187    -2.235690    -2.531153   
max       4.966414     3.479689     2.660597     1.899798     2.147015   

               5            6            7            8            9    ...  \
count  4998.000000  4998.000000  4998.000000  4998.000000  4998.000000  ...   
mean     -2.866306    -2.272845    -1.797754    -1.409784    -0.935806  ...   
std       0.906312     0.731594     0.622794     0.636863     0.657788  ...   
min      -5.330194    -4.782240    -4.311288    -4.071361    -4.142476  ...   
25%      -3.480666    -2.779832    -2.165808    -1.773870    -1.362003  ...   
50%      -2.947061    -2.285427    -1.750084    -1.422457    -0.910384  ...   
75%      -2.398797    -1.823480    -1.484107    -1.063592    -0.476477  ...   
max       1.614375     1.868728     1.804251     1.683730     1.898627  ...   

               131          132          133          134          135  \
count  4998.000000  4998.000000  4998.000000  4998.000000  4998.000000   
mean      0.071312    -0.062622    -0.276086    -0.507750    -0.761323   
std       1.404425     1.646105     1.894515     2.059366     2.086130   
min      -4.167040    -4.557576    -4.530488    -4.563270    -5.150100   
25%      -1.087720    -1.588237    -2.146835    -2.730750    -3.031224   
50%       0.658318     0.717808     0.604747     0.334857    -0.030767   
75%       1.169392     1.238651     1.264379     1.234408     1.033957   
max       3.007606     2.854680     2.912394     2.937685     3.351437   

               136          137          138          139          140  
count  4998.000000  4998.000000  4998.000000  4998.000000  4998.000000  
mean     -0.835173    -0.642739    -0.487667    -0.706574     0.584034  
std       2.056296     1.859409     1.831088     1.414414     0.492937  
min      -4.880460    -5.496107    -5.880890    -6.092227     0.000000  
25%      -2.868603    -2.154560    -1.658289    -1.596809     0.000000  
50%      -0.195151    -0.194423    -0.160262    -0.568443     1.000000  
75%       0.945027     0.951621     1.002628     0.271635     1.000000  
max       3.432519     3.579448     4.425976     7.402103     1.000000  

[8 rows x 141 columns]

In [8]:
print(ecg_data.isnull().mean())

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
136    0.0
137    0.0
138    0.0
139    0.0
140    0.0
Length: 141, dtype: float64


In [9]:
print(ecg_data.dtypes)

0      float64
1      float64
2      float64
3      float64
4      float64
        ...   
136    float64
137    float64
138    float64
139    float64
140    float64
Length: 141, dtype: object


In [13]:
X = ecg_data.iloc[:, :-1]
Y = ecg_data.iloc[:, -1]
X.head()

0         1         2         3         4         5         6    \
0 -0.112522 -2.827204 -3.773897 -4.349751 -4.376041 -3.474986 -2.181408   
1 -1.100878 -3.996840 -4.285843 -4.506579 -4.022377 -3.234368 -1.566126   
2 -0.567088 -2.593450 -3.874230 -4.584095 -4.187449 -3.151462 -1.742940   
3  0.490473 -1.914407 -3.616364 -4.318823 -4.268016 -3.881110 -2.993280   
4  0.800232 -0.874252 -2.384761 -3.973292 -4.338224 -3.802422 -2.534510   

        7         8         9    ...       130       131       132       133  \
0 -1.818286 -1.250522 -0.477492  ...  0.160348  0.792168  0.933541  0.796958   
1 -0.992258 -0.754680  0.042321  ...  0.560327  0.538356  0.656881  0.787490   
2 -1.490659 -1.183580 -0.394229  ...  1.284825  0.886073  0.531452  0.311377   
3 -1.671131 -1.333884 -0.965629  ...  0.491173  0.350816  0.499111  0.600345   
4 -1.783423 -1.594450 -0.753199  ...  0.966606  1.148884  0.958434  1.059025   

        134       135       136       137       138       139  
0  0.578621  0.257740  0.228077  0.123431  0.925286  0.193137  
1  0.724046  0.555784  0.476333  0.773820  1.119621 -1.436250  
2 -0.021919 -0.713683 -0.532197  0.321097  0.904227 -0.421797  
3  0.842069  0.952074  0.990133  1.086798  1.403011 -0.383564  
4  1.371682  1.277392  0.960304  0.971020  1.614392  1.421456  

[5 rows x 140 columns]

In [14]:
x_train, x_test, y_train, y_test = \
        train_test_split(X, Y, train_size=0.7, test_size=0.3, random_state= None)

In [15]:
from sklearn.discriminant_analysis import StandardScaler


scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [16]:
svm_model = SVC()
svm_model.fit(x_train, y_train)
y_pred = svm_model.predict(x_test)
accuracy_score(y_test, y_pred)
kfold_scores = cross_val_score(svm_model, x_train, y_train, cv=5)
# get the average score for the cross validation
val_acc = sum(kfold_scores) / len(kfold_scores)
print("Train Accuracy: ", svm_model.score(x_train, y_train))
print("Test Accuracy: ", accuracy_score(y_test, y_pred))
print("Cross Validation Accuracy: ", val_acc)

Train Accuracy:  0.9979988564894225
Test Accuracy:  0.9886666666666667
Cross Validation Accuracy:  0.9899938687921521


Test the Model

In [27]:
random_sample = pd.DataFrame(x_test).sample(n=1)
output = svm_model.predict(random_sample)
print(output[0])
if output[0] == 1:
    print("ADHD")
else:
    print("Non-ADHD")

1.0
ADHD
